#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	1) amixer set Master toggle > /dev/null ;;
	4) amixer set Master +5% > /dev/null ;;
	5) amixer set Master -5% > /dev/null ;;
esac

#Toggle mute
[[ $(pamixer --get-mute) = "true" ]] && echo -n 🔇 && exit
#Display volume
echo 🔊 $(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master));
