#!/bin/bash

CHOICE=$(echo -en "Screenshots\nDownloads\nDesktop\nPictures\nDocuments\nMusic" | dmenu)

case $CHOICE in
	Downloads|Desktop|Pictures|Documents|Music )
		pcmanfm ~/${CHOICE} &
		;;
	Screenshots )
		pcmanfm ~/Pictures/Screenshots &
		;;
esac