#!/bin/bash

CHOICE=`cat ~/Desktop/Scripts/sites | dmenu -l 5`

case $CHOICE in 
	Search )
		firefox --new-tab --search "`zenity --entry --text="Enter the search query"`" & disown
		;;
	* )
		firefox --new-tab $CHOICE & disown
esac
