#!/bin/bash

helptext() {
	echo "new: Incorrect usage"
	echo "Use flags to specify the type of file"
	echo "Available Flags"
	echo "==============="
	echo "	--java: A new Java template"
	echo "	--c: A new C template"
	echo "	--cpp: A new CPP template"
	echo "	--python: A new Python template"
	echo "	--bash: A new Bash template"
	echo "	--texreport: A new LaTeX Report template"
	echo "	--texarticle: A new LaTeX Article template"
}

createFile() {
	case $1 in
		--java )
			cp ~/Templates/java ./$2.java
			;;
		--c )
			cp ~/Templates/c ./$2.c
			;;
		--cpp )
			cp ~/Templates/cpp ./$2.cpp
			;;
		--python )
			cp ~/Templates/python ./$2.py
			;;
		--bash )
			cp ~/Templates/bash ./$2.sh
			chmod +x ./$2.sh
			;;
		--texreport )
			cp ~/Templates/texreport ./$2.tex
			;;
		--texarticle )
			cp ~/Templates/texarticle ./$2.tex
			;;
		* )
			helptext
			;;
	esac
}

NAME="new"

if [[ $# -eq 3 ]]; then
	if [[ $1 == "-o" ]]; then
		createFile $3 $2
	elif [[ $2 == "-o" ]]; then
		createFile $1 $3
	else
		helptext
	fi

elif [[ $# -eq 1 ]]; then
	createFile $1 "new"

else
	helptext

fi
