#!/bin/bash

CHOICE=`echo -en "Desktop\nDownloads\nPrograms\nSeries\nCompetitive Coding\nProjects\nOther" | dmenu`

case $CHOICE in
	"Competitive Coding" )
		DIR="~/Programs/Competitive Coding/`find ~/Programs/Competitive\ Coding -maxdepth 1 -type d | awk -F '/' '{print $6}' | dmenu -l 5`"
		;;
	Programs )
		DIR=~/Programs/`find ~/Programs -maxdepth 1 -type d | awk -F '/' '{print $5}' | dmenu -l 5`
		;;
	Projects )
		DIR=~/Projects/`find ~/Projects/ -maxdepth 1 -type d | awk -F '/' '{print $4}' | dmenu -l 5`
		;;
	Other )
		DIR=~/`find ~ -maxdepth 1 -type d | awk -F '/' '{print $4}' | dmenu -l 5`
		;;
	Series )
		DIR="~/Videos/Series/`find ~/Videos/Series/ -maxdepth 1 -type d | awk -F '/' '{print $6}' | dmenu -l 5`"
		;;
	* )
		DIR=~/$CHOICE
		;;
esac

st -n floatterm -e ranger $DIR
