#!/bin/bash

length=$(($#-1))
case $1$2 in
	*hour*|*minute*|*day*)
		echo "notify-send ${@:$#} && mpv ~/Desktop/Scripts/notify.ogg >> /dev/null" | at now + ${@:1:$length}
		;;
	*)
		echo "notify-send ${@:$#} && mpv ~/Desktop/Scripts/notify.ogg >> /dev/null" | at ${@:1:$length}
		;;
esac
