#!/bin/bash

CHOICE="$(echo -en 'List\nAdd Entry\nMark as Done' | dmenu -l 3)"

case $CHOICE in
	"List")
		st -e zsh -c 'todo -l|less'
		;;
	"Add Entry")
		st -e zsh -c 'echo "Enter the task"; read task; todo $task; todo -l|less'
		;;
	"Mark as Done")
		todo -d
		;;
esac
